# Generated by Django 5.1 on 2024-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='documentNumber',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='receivedDate',
            field=models.DateTimeField(),
        ),
    ]
