# Generated by Django 5.1 on 2024-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0002_equipment_documentnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='postalCode',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='garanty',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
