# Generated by Django 5.1 on 2024-09-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0003_client_postalcode_equipment_garanty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='garanty',
            new_name='warranty',
        ),
    ]
