# Generated by Django 5.1.2 on 2024-11-02 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0004_rename_garanty_equipment_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nif',
            field=models.IntegerField(default=111111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='warrantyDate',
            field=models.DateField(default=datetime.datetime(2024, 11, 2, 23, 6, 58, 261768, tzinfo=datetime.timezone.utc)),
        ),
    ]
