# Generated by Django 5.1.2 on 2024-11-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0005_client_nif_equipment_warrantydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='clientNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warrantyDate',
            field=models.DateField(),
        ),
    ]
