# Generated by Django 5.1.2 on 2024-11-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0006_equipment_clientnumber_alter_equipment_warrantydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='clientNumber',
            new_name='receiptNumber',
        ),
        migrations.AddField(
            model_name='client',
            name='clientNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='documentNumber',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warrantyDate',
            field=models.DateField(null=True),
        ),
    ]
