# Generated by Django 5.1.1 on 2024-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0007_rename_clientnumber_equipment_receiptnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='partsIva',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
