# Generated by Django 5.1.1 on 2024-11-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0009_equipment_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='parts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='RestFramework.equipmentpart'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='partsIva',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='receiptNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warrantyDate',
            field=models.DateField(),
        ),
    ]
