# Generated by Django 5.1.1 on 2024-11-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0011_alter_client_address_alter_client_clientnumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='parts',
        ),
        migrations.AddField(
            model_name='equipmentpart',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='RestFramework.equipment'),
            preserve_default=False,
        ),
    ]
