# Generated by Django 5.1.2 on 2024-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0013_alter_equipmentpart_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phoneNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='receiptNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='receivedDate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warrantyDate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
