# Generated by Django 5.1.2 on 2024-11-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0014_alter_client_clientnumber_alter_client_nif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='partsIva',
            field=models.TextField(blank=True, null=True),
        ),
    ]
